//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureManagmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemTur
    {
        public int islemTurID { get; set; }
        public string islemTuru { get; set; }
        public string islemTurBilgi { get; set; }
    }
}
