//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureManagmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public int islemID { get; set; }
        public Nullable<int> islemTurID { get; set; }
        public Nullable<int> perID { get; set; }
        public Nullable<int> islemRefID { get; set; }
        public Nullable<System.DateTime> islemTarih { get; set; }
    }
}
