//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureManagmentApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokDBEntities : DbContext
    {
        public StokDBEntities()
            : base("name=StokDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AtikKontrol> AtikKontrols { get; set; }
        public virtual DbSet<Bolumler> Bolumlers { get; set; }
        public virtual DbSet<Islemler> Islemlers { get; set; }
        public virtual DbSet<IslemTur> IslemTurs { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<PersonelTip> PersonelTips { get; set; }
        public virtual DbSet<SatinAlma> SatinAlmas { get; set; }
        public virtual DbSet<Stok> Stoks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<UrunTur> UrunTurs { get; set; }
        public virtual DbSet<Zimmet> Zimmets { get; set; }
    }
}
