//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureManagmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlma
    {
        public int saID { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<System.DateTime> saTarih { get; set; }
        public Nullable<int> perID { get; set; }
        public Nullable<decimal> saBirimFiyat { get; set; }
        public Nullable<int> saAdet { get; set; }
        public string saTedarikciFirma { get; set; }
    }
}
