//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureManagmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int urunID { get; set; }
        public string urunBilgi { get; set; }
        public string urunOzellik { get; set; }
        public Nullable<int> urunTurID { get; set; }
    }
}
