//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureManagmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmet
    {
        public int zimmetID { get; set; }
        public Nullable<bool> zimmetAktif { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<int> perID { get; set; }
        public Nullable<System.DateTime> zimmetTarih { get; set; }
    }
}
